/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.multiscrap.telas;

import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author dryro
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private JDesktopPane jDesktopPane;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/Image/img1.jpg"));
        Image img = icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img ,0,0,getWidth(),getHeight(),this);
            }
        };
        lblData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuClientes = new javax.swing.JMenu();
        MenuClientesCad = new javax.swing.JMenuItem();
        MenuClientesPes = new javax.swing.JMenuItem();
        MenuEnc = new javax.swing.JMenu();
        MenuEncCad = new javax.swing.JMenuItem();
        MenuEncVis = new javax.swing.JMenuItem();
        MenuUsers = new javax.swing.JMenu();
        MenuUsersAlt = new javax.swing.JMenuItem();
        MenuProdutos = new javax.swing.JMenu();
        MenuCadProdutos = new javax.swing.JMenuItem();
        MenuOpt = new javax.swing.JMenu();
        MenuOptSair = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multiscrap Papelaria Personalizada");
        setBackground(new java.awt.Color(252, 252, 252));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblData.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        lblData.setText("Data");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/multiscrap/icones/logo Multiscrap jpeg (1)_Easy-Resize.com.jpg"))); // NOI18N

        Menu.setBackground(new java.awt.Color(29, 123, 148));

        MenuClientes.setText("Clientes");

        MenuClientesCad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        MenuClientesCad.setText("Cadastrar");
        MenuClientesCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesCadActionPerformed(evt);
            }
        });
        MenuClientes.add(MenuClientesCad);

        MenuClientesPes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        MenuClientesPes.setText("Pesquisar");
        MenuClientesPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesPesActionPerformed(evt);
            }
        });
        MenuClientes.add(MenuClientesPes);

        Menu.add(MenuClientes);

        MenuEnc.setText("Encomendas");
        MenuEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEncActionPerformed(evt);
            }
        });

        MenuEncCad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        MenuEncCad.setText("Cadastrar");
        MenuEncCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEncCadActionPerformed(evt);
            }
        });
        MenuEnc.add(MenuEncCad);

        MenuEncVis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        MenuEncVis.setText("Visualizar");
        MenuEncVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEncVisActionPerformed(evt);
            }
        });
        MenuEnc.add(MenuEncVis);

        Menu.add(MenuEnc);

        MenuUsers.setText("Usuários");

        MenuUsersAlt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        MenuUsersAlt.setText("Alterar/Adicionar/Excluir");
        MenuUsersAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsersAltActionPerformed(evt);
            }
        });
        MenuUsers.add(MenuUsersAlt);

        Menu.add(MenuUsers);

        MenuProdutos.setText("Produtos");

        MenuCadProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadProdutos.setText("Cadastro/Alteração");
        MenuCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadProdutosActionPerformed(evt);
            }
        });
        MenuProdutos.add(MenuCadProdutos);

        Menu.add(MenuProdutos);

        MenuOpt.setText("Opções");

        MenuOptSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuOptSair.setText("Sair");
        MenuOptSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOptSairActionPerformed(evt);
            }
        });
        MenuOpt.add(MenuOptSair);

        Menu.add(MenuOpt);

        MenuAjuda.setText("Ajuda");

        MenuAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenuAjudaSobre.setText("Sobre");
        MenuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudaSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuAjudaSobre);

        Menu.add(MenuAjuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblData)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblData)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addContainerGap(173, Short.MAX_VALUE))
            .addComponent(Desktop)
        );

        setSize(new java.awt.Dimension(1037, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Substituindo a lblData pela data atual
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenuOptSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOptSairActionPerformed
        //exibe a caixa de diálogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuOptSairActionPerformed

    private void MenuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudaSobreActionPerformed
        //chamando a tela sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MenuAjudaSobreActionPerformed

    private void MenuUsersAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsersAltActionPerformed
        //Tela usuário
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_MenuUsersAltActionPerformed

    private void MenuClientesCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesCadActionPerformed
        //Tela cadastro de clientes
        TelaCadastroCliente cadastroCli = new TelaCadastroCliente();
        cadastroCli.setVisible(true);
        Desktop.add(cadastroCli);
    }//GEN-LAST:event_MenuClientesCadActionPerformed

    private void MenuClientesPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesPesActionPerformed
        // Tela pesquisa cliente
        TelaCliente pesquisaCli = new TelaCliente();
        pesquisaCli.setVisible(true);
        Desktop.add(pesquisaCli);
    }//GEN-LAST:event_MenuClientesPesActionPerformed

    private void MenuEncCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEncCadActionPerformed
        TelaCadastroEnc enc = new TelaCadastroEnc();
        enc.setVisible(true);
        Desktop.add(enc);
    }//GEN-LAST:event_MenuEncCadActionPerformed

    private void MenuEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEncActionPerformed
        
    }//GEN-LAST:event_MenuEncActionPerformed

    private void MenuEncVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEncVisActionPerformed
        TelaEncomendas enc2 = new TelaEncomendas();
        enc2.setVisible(true);
        Desktop.add(enc2);
    }//GEN-LAST:event_MenuEncVisActionPerformed

    private void MenuCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadProdutosActionPerformed
        TelaProdutos pr = new TelaProdutos();
        pr.setVisible(true);
        Desktop.add(pr);
    }//GEN-LAST:event_MenuCadProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenuItem MenuAjudaSobre;
    private javax.swing.JMenuItem MenuCadProdutos;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenuItem MenuClientesCad;
    private javax.swing.JMenuItem MenuClientesPes;
    private javax.swing.JMenu MenuEnc;
    private javax.swing.JMenuItem MenuEncCad;
    private javax.swing.JMenuItem MenuEncVis;
    private javax.swing.JMenu MenuOpt;
    private javax.swing.JMenuItem MenuOptSair;
    private javax.swing.JMenu MenuProdutos;
    private javax.swing.JMenu MenuUsers;
    private javax.swing.JMenuItem MenuUsersAlt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblData;
    // End of variables declaration//GEN-END:variables
}
